### ISSUE TITLE
Samples loading Go built .dll's into C# using P/Invoke

### ISSUE THREAD

**Issue by johncburns1** [dotnet/samples#3689]
Right now we are looking into loading shared-c libraries built from Golang code (using cgo) into our C# project. There is not much documentation on how to import .dll's built from Golang code into .NET, so I spent a little time working through this and constructed a pretty solid and varied array of examples that could be useful for others in the future looking to do the same thing. Especially since Go is becoming more of a prominent tool as it matures.

If you guys are interested in putting some samples out for the public to use, let me know. Not looking for any ownership or anything, just think that it would be helpful to others looking to use P/Invoke to import Go built .dlls or other shared-c libraries into C# code.

Repo is [here](https://github.com/johncburns1/Golang-.NET-SharedC)

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [ ] .NET Core 3
- [ ] .NET Framework 4.8

I originally created the issue in dotnet/docs [here](https://github.com/dotnet/docs/issues/13430) and was instructed to bring it to samples instead.  I do think this would be a good addition because this practice is becoming more prevalent.

**Comment by adegeo** [comment]
Sounds good! The structure of a sample is pretty easy to handle. Create a new directory here: https://github.com/dotnet/samples/tree/master/core/interop as this seems to be the appropriate folder. I'm not sure what directory name would be good, but maybe **godll** or something. (not simply "go" though as we don't want to confuse it with a language-specific folder. 

Then, create a subfolder named "cs" and have your csharp project and code in that folder. Include a readme.md file and make sure to add the metadata so that the sample will be searchable via https://docs.microsoft.com/en-us/samples/browse/

So I think your folder path would be something like `/core/interop/godll/cs/`

Here is an example readme (and sample) with some metadata you can use as a template: https://github.com/dotnet/samples/tree/master/core/encoding/cyrillic-to-latin/cs

**Comment by adegeo** [comment]
@johncburns1 Thank you again for the submission. I'm going to close this issue per the comments in the related PR.
